apiDomain="https://hms-sit.test-cignacmb.com/hmc_cmb_server";
loginApi="/login";
getUserInfoApi="/getUserInfo";
getUserTaskInfoApi="/getUserTaskInfo";
rankListApi="/rankList";
genInviteCodeApi="/genInviteCode";
acceptInviteApi="/acceptInvite";
saveUserProfileApi="/saveUserProfile";
searchFriendApi="/searchFriends";
sendInviteApi="/sendInvite";
inviteListApi="/inviteList";
getSysTaskListApi="/getSysTaskList";
createTaskApi="/createTask";
uploadDaysDataApi="/uploadAppData";
getSysAdvertisingApi='/getSysAdvertising';
delInviteApi='/delInvite';
sendSMSForUserApi='/sendSMSForUser';
saveUserPhoneApi='/saveUserPhone';
shareApi='/share';
updateTaskIsShowApi='/updateTaskIsShow';
cancelUserTaskApi='/cancelUserTask';
addUserSuggestApi='/addUserSuggest';
redirectMD5PathApi='/redirectMD5Path';
saveArticleLikeApi="/saveArticleLike";
getArticleLikeApi="/getArticleLike";
htListApi="healthyTrouble/list.json";
topicListApi="hotTopic/list.json";

//HRA
cignaDomain="https://hms-sit.test-cignacmb.com/hmc_hra_server";
getSubmitEltResultApi="/submitAllEltResult";
getEltResultApi="/getHealthReport";
getHealthyTaskSetApi="/getHealthPlan";
getHealthyTaskSetUpdateApi = "/updateHealthPlan";
getHealthyTaskRecordApi = "/getHealthRecord";
getHealthyTaskRecordUpdateApi = "/updateHealthRecord";
getAllEvaluationApi="/getAllEvaluation";
getCmEvaluationApi='/getCmEvaluation';
submitCmEvaResultApi='/submitCmEvaResult';
getCmEvaResultApi='/getCmEvaResult';
getHealthSuggestionApi='/getHealthSuggestion';
getHealthStatusApi="/getHealthStatus";

//RUNGROUP
rungroupDomain="https://hms-sit.test-cignacmb.com/hmc_rungroup_server";
createGroupApi = "/createGroup";
getRecommendGroupsAPi = "/getRecommendGroups"
getGroupListApi = "/getGroupList";
getGroupInfoApi = "/getGroupInfo";
joinGroupApi = "/joinGroup";
cancelJoinApi = "/cancelJoin";
exitGroupApi = "/exitGroup";
acceptJoinGroupApi = "/acceptJoinGroup";
refuseJoinGroupApi = "/refuseJoinGroup";
updateGroupLeadApi = "/updateGroupLead";
getGroupRankApi = "/getGroupRank";
getMemberRankApi = "/getMemberRank";
getMemberListApi = "/getMemberList";
delMemeberApi = "/delMemeber";
saveShareMessageApi = "/saveShareMessage";
getStatusUserInGroupApi = "/getStatusUserInGroup";
getMessageApi = "/getMessage";
delMessageApi = "/delMessage";

exchangeDomain="https://hms-sit.test-cignacmb.com/hmc_coinfree_server/activity";
getProductListApi="/getProductList";//健康币兑换产品列表
getProductByCordApi="/getProductByCord";//健康币兑换产品详情
addInsureApi="/addInsure";//健康币兑换提交投保接口
gainScoreApi="/gainScore";//每日健康币领取
getTaskInfoApi="/getTaskInfo";//获取悬赏任务信息
getTaskScoreApi="/getTaskScore";//领取悬赏任务健康币
getTaskTroubleApi="/getTaskTrouble";//完成一次健康困扰
expendScoreRrewardTaskApi="/expendScoreRrewardTask";//完成一次健康币兑换任务
